# main menu navigation
menu:
  Home: /
  Archives: /archives
  # Tags: /tags
  # Category: /categories
  # About: /about
  # Contact: 
  

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css
- /css/lib_zoom.css
- https://fonts.cat.net/css?family=Libre+Barcode+39|Source+Code+Pro|Cormorant+Garamond

# scripts loaded in the end of the body
scripts:
- /js/lib/zoom-vanilla.min.js
- /js/main.js # main.js务必位于最后

# Customize
customize:
    favicon: /css/images/favicon.ico

# Plugins
plugins:
  google_analytics:  # enter the tracking ID for your Google Analytics

# comments only support hypercomments
comments:
  enable: true
  hypercomments:  #id

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:

sitemap:
    path: sitemap.xml
